Upgrade debian based systems
stuvusIT/upgrade pull request #1
Opened 2017-06-15 19:21 UTC by Mr-Pi

* task to upgrade and show upgradable packages on debian systems
* Add Doku
* Add LICENSE

2017-06-15 22:21 UTC, SlothOfAnarchy requested changes

2017-06-15 22:21 UTC, SlothOfAnarchy commented on tasks/upgrade_debian.yml
> +  apt: update_cache=yes
please indent

2017-06-15 22:21 UTC, SlothOfAnarchy commented on tasks/upgrade_debian.yml
> +  shell: aptitude -q -F%p --disable-columns search '~U'
is aptitude available on all Debian-based releases?

2017-06-15 22:21 UTC, SlothOfAnarchy commented on tasks/upgrade_debian.yml
> +  apt: upgrade=safe
indent

2017-06-15 22:21 UTC, SlothOfAnarchy commented on tasks/upgrade_debian.yml
> +- name: List services to restart (2/2)
Would it be a good idea to include a task that restarts these services?

2017-06-15 22:21 UTC, SlothOfAnarchy commented on README.md
> +# Role Name
change the name

2017-06-15 22:21 UTC, SlothOfAnarchy commented on README.md
> +## Dependencies
remove all these unnecessary headings

2017-06-16 11:08 UTC, Mr-Pi commented
Please rereview

2017-06-16 11:12 UTC, SlothOfAnarchy commented
@Mr-Pi If you set the role name in readme and remove the empty sections, you're good to go!

2017-06-16 11:39 UTC, Mr-Pi commented
@SlothOfAnarchy what you mean, they are set correctly

2017-06-16 13:13 UTC, SlothOfAnarchy commented
I'm sorry, I didn't see the changed role name. `Role Variables`, `Dependencies` and `Example Playbook` are still empty sections though. Please fill or remove them.

2017-06-16 15:18 UTC, SlothOfAnarchy submitted a review, later dismissed

2017-06-16 15:18 UTC, SlothOfAnarchy commented on README.md
> +| upgrade_restart_services | boolean | true    | Automatically restart services, when needed(for ex. linked libaries are updated) |     N    |
use code formatting

2017-06-16 15:18 UTC, SlothOfAnarchy commented on tasks/upgrade_debian.yml
> +  when: services.stdout_lines and upgrade_restart_services
we could also use a tag for this, what do you think?

2017-06-16 15:18 UTC, SlothOfAnarchy commented on README.md
> +	* aptitude
fix list formatting

2017-06-16 15:18 UTC, Mr-Pi commented
Is fixed

2017-06-16 15:18 UTC, Mr-Pi commented on README.md
> +| upgrade_restart_services | boolean | true    | Automatically restart services, when needed(for ex. linked libaries are updated) |     N    |
what you mean?

2017-06-16 21:40 UTC, Mr-Pi commented
Okay, please rereview :)

2017-06-17 10:15 UTC, SlothOfAnarchy commented on README.md
> +| upgrade_restart_services | boolean | true    | Automatically restart services, when needed(for ex. linked libaries are updated) |     N    |
`upgrade_restart_services` instead of upgrade_restart_services

2017-06-17 10:18 UTC, SlothOfAnarchy approved these changes
Yes, now I like it, thanks! We can still talk about using a tag instead of the var `upgrade_restart_services`.

2017-06-17 10:18 UTC, merged